### PR TITLE
Multi input

### PR DESCRIPTION
**Pull request by Chris7**
This is the initial work to address issue #7.  It's not complete yet, but I'd like to open up discussion on the interface @mfitzp.

### CODE REVIEW

**Comment by mfitzp** [comment]
Nice work @Chris7 

From the linked issue I see this is addressing the argparse `+` style (and `?` `*` `N` variations) for accepting multiple inputs for a given parameter - but so far only for choice fields (where there are restricted choices). So in that case, rather than present multiple single-choice drop downs here you present a single multi-choice field? Seems like a sensible approach.

How will you handle the `N` case with a specific number of options required (i.e. exactly N) the HTML select multiple doesn't support an upper limit (and the only lower limit is 1) though you can do something with jQuery to the effect:

```
$("select").on("click", "option", function () {
    if ( 3 <= $(this).siblings(":selected").length ) {
        $(this).removeAttr("selected");
    }
});
```

I'm moving helper functions in a core js file as part of the UI overhaul so these sorts of things can end up there and be applied using data attributes on the elements themselves, e.g. `<select wooey-data-select-minimum="3" wooey-data-select-maximum="5">`

Are you planning a more generic way to handle the other multiple input fields? Or is that for a future time?

Just to let you know I'm off to sunny Greece for a week in a few hours. I'll take a closer look at this (and your progress on it) when I get back.

(off-topic) FYI the work on the interface has begun. I should have a PR to consider shortly after I'm back.

**Comment by Chris7** [comment]
Choice_limit actually doesn't care about the 'choices' field. So it's a bit of a misnomer, arg_limit might be a better term. It was crafted with multiple file uploads in mind without having to implement a backend for handling that. So other multiple input fields are already supported.

For the N case, I was going to handle it in form validation, but I think it's important for the user to be notified as well they are above the limit. So I agree with your approach. I think changing the multiple_choices property to arg_limits that returns a (min, max) and None for unlimited would be better (ie we can do (1, None) for required fields without a cap, (None, None) for no limits in both directions, etc.).

I'd also like to make it more generic, I don't like using field._wooey_multi_field and fetching a new parameter from the JSON. I'd rather have all these additions added in the form rendering, but I haven't figured out the best way to accomplish this (I don't want to make a new mixin for every field type for instance). This would also automatically handle the addition of data-wooey-select-minimum/etc. I'll look more into this.

Enjoy Greece! I'm excited to see the UI.

**Comment by mfitzp** [comment]
Choosing the appropriate widget for the form without it descending into a long tree of if-else in the template was one of the tricky things I came up against in the flask version. But then splitting every possible combo into multiple template mixing isn’t any better (duplicated code).

Perhaps if we can define a core set of widgets and then control them using class or data attributes. We effectively create custom widgets at the JS level while keeping the template core relatively straightforward. This will probably benefit us in the long run for dynamically adding additional fields etc. also.

Ideally I guess there should be a single mapping from the type parameter on the argparse to the field. We can combine where it makes sense (e.g. should text, int and float inputs get the same mixin?) as needed. I think this should be manageable.

On 6 July 2015 at 20:20:56, Chris Mitchell (notifications@github.com) wrote:

Choice_limit actually doesn't care about the 'choices' field. So it's a bit of a misnomer, arg_limit might be a better term. It was crafted with multiple file uploads in mind without having to implement a backend for handling that. So other multiple input fields are already supported.

For the N case, I was going to handle it in form validation, but I think it's important for the user to be notified as well they are above the limit. So I agree with your approach. I think changing the multiple_choices property to arg_limits that returns a (min, max) and None for unlimited would be better (ie we can do (1, None) for required fields without a cap, (None, None) for no limits in both directions, etc.).

I'd also like to make it more generic, I don't like using field._wooey_multi_field and fetching a new parameter from the JSON. I'd rather have all these additions added in the form rendering, but I haven't figured out the best way to accomplish this (I don't want to make a new mixin for every field type for instance). This would also automatically handle the addition of data-wooey-select-minimum/etc. I'll look more into this.

Enjoy Greece! I'm excited to see the UI.

**Comment by Chris7** [comment]
I actually figured it out. Just needed a break from coding I guess. We can do all this logic like this:
`
field.widget.attrs.update({
                'data-test': 'here'
            })
`

Then we can do whatever we want with javascript for the front-end needs.

**Comment by Chris7** [comment]
Support for cloning jobs where multiple inputs per parameter is added. Also a ton of simplification of the javascript with a better UI. 

Next item is handling cases where the input expects exactly N arguments. This needs to be handled for multiple choice fields and cases for my generic multi-input. It can be added to the widget_data_dict for multiple choice fields, and I'm still pondering the best place for the generic cases.

After that I think error handling needs to be looked at again (providing form errors to the user). It might just work out of the box.

Following this, I think all that remains are building new test cases, and it's ready for prime time.

**Comment by Chris7** [comment]
Error handling seems to just work. I'm a bit worried about using monkey patching to accomplish everything thus far, though I find it hard to believe Django would change the method signatures.

**Comment by mfitzp** [comment]
We can look later to see if there are alternative ways to accomplish this - for now "it works" is great news! Nice work.

I think the most sensible thing would be for this to be merged into master once complete (tests, etc.) and then I can re-base the UI changes on top of it. There will probably be a few conflicts that need resolving in the templates.

**Comment by Chris7** [comment]
Choice limits added for both cases. Just units tests left.

**Pull request merged**
